### ISSUE TITLE
Telecarla Installation 

### ISSUE THREAD

**Issue by XengardenORG** [hofbi/telecarla#49]
Hello and thank you for making this awesome tool for interacting with CARLA. I am very new to CARLA and ROS and was wondering if you could point me in the right direction with installing telecarla.

from my understand these are the steps i need to follow:

step1 .Download version of Carla you want (9.10.1 tar.gz)
- we install the version of Carla as well?

step2 install ROS and catkin_tools
- pretty straight forward for me (add keys and apt install both packages)

step3 create workspace 
- straight forward (make directory and change into the directory

step4 Clone Repo 
- I think I cloned the repo correctly ( git clone -b carla-0.9.10.1  https://github.com/hofbi/telecarla.git)

step5 run install script (does it need to be root/sudo?

step6 source workspace 

--------------------------
Running telecarla

I understand we installed and setup carla along with the telecarla extension. do we need to install the same packages on the remote client (say another ubuntu 18.04) or just the telecarla gui that interact with the telecarla server? 

Sorry again if I'm not understanding the way telecarla is built.

Thanks again!

**Comment by hofbi** [comment]
Right, you need telecarla on both server and client machine. Carla itself and the carla-ros-bridge is sufficient on the server side only. Basically the green components in [this image](https://github.com/hofbi/telecarla#telecarla) are from telecarla. So the easiest solution is to do the same setup on both machinces, just skip the first step (download carla) on the client PC.

**Comment by XengardenORG** [comment]
I still wasn't able to get it working.... I think im configuring something with catkin_tools incorrectly. Do you have a packaged  ubuntu 18.04 or 20.04 .tar with everything installed you could upload?

**Comment by hofbi** [comment]
Right, docker takes care about the full setup.

1. On the server side, open a terminal and run the CARLA server 0.9.12
2. Open a second terminal and run `docker compose run telecarla`. If you do this for the first time it will run for some time since it has to download and configure the environment. After it finished you should see a terminal that has the environment ready and you can continue running the commands you want.
3. On your client machine, run `docker compose run telecarla` as well

**Comment by hofbi** [comment]
Seems to be resolved
